### PR TITLE
Moving documentation away from ``phys2bids`` to physiopy

### PR DESCRIPTION
**Pull request by sangfrois**
## What I did
- I moved the `readthedocs.yml` to physiopy
- I used [``sphinx-multibuild``](https://github.com/NSLS-II/sphinx-multibuild) to use two input directories in the build.
```
sphinx-multibuild -m -i ./docs -i ../phys2bids/docs -s ./build/docs/tmp -T -o _build/doctrees-readthedocs -D language=en -b html
```
``-m``  Citing ``sphinx-multibuild`` tool repo : "*Using the -m option will continuously build the output when anything changes in any of the input directories.*"

``-s`` here is the path to symlinks. I don't know... do we want them ?

I'm learning Sphinx as I go, sorry! Now ...
## What do we miss ?
- I get these warnings and want to make sure it doesn't cause anything to fail. Sorry for the lazy snap, but here it is:
image

- Should I run ``multibuild`` with all physiopy's repos as inputs ?

### CODE REVIEW

**Comment by eurunuela** [comment]
Thank you @sangfrois ! I've just installed the necessary dependencies and will have a look.

I will let you know once I have explored this a bit.

**Comment by smoia** [comment]
Hey @sangfrois ! I just realised that this document re-positioning might be a bit more complicated than expected, sorry :sweat_smile: .

Why don't you write the paragraphs that you originally wanted to add, and today after 18 our time we meet up and discuss a bit about it?

**Comment by eurunuela** [comment]
I think we can make it work with `git add submodule`.

Let me try!

**Comment by sangfrois** [comment]
@eurunuela ; right ! I hadn't thought of that one. May be simpler.

I totally get your point, @smoia ! LOL it was the same with multi-run. We thought of it as being super easy, then we realised how complicated it could be.

Lemme know when you guys want to chat, I'll update you on my project also.

**Comment by eurunuela** [comment]
Let's meet after the unconferences!

**Comment by smoia** [comment]
Yeah, I can't join you, but pay attention that the readthedocs rendering might actually not start automatically when a submodule is updated.

**Comment by eurunuela** [comment]
Hey @sangfrois , now that we're working on `physiopy.github.io`, how about we close this?

**Comment by sangfrois** [comment]
Sure let's close this!

**Pull request closed without merging**
